# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['solace_browser_server.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('web', 'web'),
        ('static', 'static'),
        ('data', 'data'),
    ],
    hiddenimports=[
        'competitive_features',
        'history',
        'oauth3',
        'audit',
        'audit.chain',
        'audit.alcoa',
        'audit.retention',
        'browser',
        'sync_client',
        'evidence_upload',
        'llm',
        'llm.claude_code_client',
        'llm.noop_client',
        'yinyang',
        'yinyang.top_rail',
        'yinyang.bottom_rail',
        'yinyang.ws_bridge',
        'yinyang.push_alerts',
        'yinyang.delight_engine',
        'yinyang.state_bridge',
        'yinyang.alert_queue',
        'yinyang.support_bridge',
        'yinyang.highlighter',
        'agents',
        'api',
        'approvals',
        'channels',
        'cli',
        'cross_app',
        'fs_gateway',
        'machine',
        'plugins',
        'profiles',
        'recipes',
        'store_client',
        'voice',
        # web UI dashboard server + its dependencies
        'web',
        'web.server',
        'app_store',
        'app_store.backend',
        'companion',
        'companion.apps',
        'companion.bridge',
        'companion.builtin',
        'companion.scopes',
        'inbox_outbox',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['django', 'django.utils', 'django.core'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='solace-browser',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resources/windows/solace-browser.ico',
    version='resources/windows/version_info.txt',
)
