// Diagram: 05-solace-runtime-architecture
pub mod agents;
pub mod app_engine;
pub mod cloud;
pub mod config;
pub mod cron;
pub mod crypto;
pub mod event_log;
pub mod evidence;
pub mod mcp;
pub mod persistence;
pub mod pzip;
pub mod recipe;
pub mod routes;
pub mod server;
pub mod state;
pub mod utils;

pub use server::build_router;
pub use state::AppState;
